#!/usr/bin/env bash
set -euo pipefail

# Get HDMI status
HDMI_STATUS1=$(xrandr | grep "HDMI-1 connected")
HDMI_STATUS2=$(xrandr | grep "HDMI-2 connected")

if [[ -n "$HDMI_STATUS1" ]]; then
    xrandr --output eDP-1 --off --output HDMI-2 --off --output HDMI-1 --auto --primary --mode 1920x1080 --rate 60
elif [[ -n "$HDMI_STATUS2" ]]; then
    xrandr --output eDP-1 --off --output HDMI-1 --off --output HDMI-2 --auto --primary --mode 1920x1080 --rate 60
else
    xrandr --output eDP-1 --auto --primary --output HDMI-1 --off --output HDMI-2 --off
fi
